services:
  pg:
    image: postgres:latest
    environment:
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=pgpwd
      - POSTGRES_DB=pgdb
    ports:
      - 5432:5432
    shm_size: 128mb
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U pguser -d pgdb']
      interval: 5s
      timeout: 5s
      retries: 5

  holo:
    image: holostudio/studio:latest
    ports:
      - 23806:23806
    environment:
      - DB_TYPE=postgres
      - DB_USER=pguser
      - DB_PASSWORD=pgpwd
      - DB_HOST=pg
      - DB_PORT=5432
      - DB_NAME=pgdb
      - SSL_MODE=disable
    depends_on:
      pg:
        condition: service_healthy
